#Creación de una action propia
name: "my action"
description: "Test my action"
## Se define el nombre de la acción  o para qué se va a utilizar
inputs:
#se define el nombre de la acción así como los parámetros que se van a utilizar
  message:
    description: "Mensaje de saludo"
    required: true
    default: "Hola Mundo"
  
runs:
    #COMPOSITE: permite agrupar varios pasos en una sola acción los cuales son comunes
  using: "composite"

  steps:
    - name: "Hola Mundo"
      run: echo "Hola ${{ inputs.message }}"
      shell: bash