# Proceso de ejecución de comandos
name: Test
 
on: [push]

#workflow_dispatch: 
#Prueba de ejecución de comandos
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: ls
        uses: ./.github/actions/my-action
