# Proceso de ejecución de comandos
name: Test

on: [push]
#Prueba de ejecución de comandos
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: ls
      #instalación de paquetes cuando se debe usar múltilinea |
        run:  |
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

